---
apiVersion: v1
kind: Service
metadata:
  name: llama-stack-playground
  namespace: {{ .Values.username }}-llama-stack
  labels:
    app.kubernetes.io/name: llama-stack-playground
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: proxy-tls
spec:
  type: ClusterIP
  ports:
    - name: proxy
      port: 443
      targetPort: 8443
  selector:
    app.kubernetes.io/name: llama-stack-playground
